.\" Manpage for spatula.
.TH man 1 "17 January 2021" "1.0" "User Commands"
.SH NAME
spatula \- Create a dev environment quickly. 
.SH SYNOPSIS
spatula [PROJECTNAME]
.SH DESCRIPTION
Spatula is a shell script that creates a simple work environment in a few seconds. The environment is created by looking at a config file to choose what to name things.
.SH OPTIONS
Spatula does not take in any arguments from the command line. However, there are options in config.cfg
.SH BUGS
Config file could contain malicous code, so make sure to check what is in the config file.
.SH AUTHOR
Robert / Finxx1 (github.com/Finxx1)
