#!/bin/sh

if [ $# == 1 ]
then

. /opt/utensil/bin/spatula.cfg

mkdir $proj_name
cd $proj_name
mkdir $bin_name
mkdir $src_name
cd $src_name
printf "#include <stdio.h>\n\nint main(int argc, char* argv[]) {\n  \n  return 0;\n}" >> $src_main_file
cd ../
printf "all:\n\t\$(CC) -o bin/$bin_main_file src/$src_main_file -Wall -W -pedantic -std=c99" > Makefile
fi
