.\" Manpage for Fork
.TH fork 1 "11 February 2021" "1.0" "User Commands"
.SH NAME
Fork \- Catch missing line endings in C like languages. 
.SH SYNOPSIS
Fork [File]
.SH DESCRIPTION
Fork is a C program that catches lines without a proper line ending
.SH OPTIONS
Fork has a single parameter, and that is the file to read.
.SH BUGS
Comments trick the program, please use "// comment;".
.SH AUTHOR
Finxx1 (github.com/Finxx1)